import { App, TFile } from "obsidian";
import { writeUniqueNote } from "./note-export";

/** An offline, DIY checklist for replicating a whole vault's config by hand —
 * the thing Starter Packs deliberately does NOT do (see the settings help). It
 * bakes in the secrets warning so people don't leak API keys when they zip. */
export const VAULT_REPLICATION_CHECKLIST = `# Replicating a vault — checklist

Starter Packs shares a **list of plugins and themes** — it does not copy your
settings, CSS snippets, hotkeys, or the rest of your \`.obsidian\` folder. To
carry a full setup to another vault or person, zip it up yourself using the
steps below.

## Before you start
- [ ] If you only need plugins + themes, use a Starter Pack instead — it's safer and one click for the recipient.
- [ ] If you're overwriting someone else's vault, back up their \`.obsidian\` folder first.

## What lives in \`.obsidian/\` (copy what you want)
- [ ] \`plugins/<id>/\` — each plugin's code **and** its \`data.json\` (that plugin's settings)
- [ ] \`themes/\` — installed themes
- [ ] \`snippets/\` — your CSS snippets
- [ ] \`appearance.json\` — active theme, fonts, base appearance
- [ ] \`hotkeys.json\` — custom hotkeys
- [ ] \`core-plugins.json\` / \`community-plugins.json\` — which plugins are enabled
- [ ] \`app.json\` — editor / core settings

## ⚠️ Remove secrets before sharing
- [ ] Open each \`plugins/<id>/data.json\` and delete API keys, tokens, passwords, and sync credentials.
- [ ] Note: plugins that use the OS keychain keep secrets **out** of these files (safe). The risk is plugins that store them **in plaintext** in \`data.json\`.
- [ ] Remove machine-specific absolute paths (backup folders, sync targets, etc.).
- [ ] Decide whether to include \`workspace.json\` / \`workspace-mobile.json\` — these hold your exact pane layout and are usually device-specific.

## Package it
- [ ] Zip the \`.obsidian/\` folder (or the whole vault).
- [ ] Share the zip.

## On the receiving side
- [ ] Close Obsidian.
- [ ] Back up the existing \`.obsidian\` folder.
- [ ] Unzip into the vault, merging/replacing \`.obsidian\`.
- [ ] Reopen Obsidian; review and enable the plugins.

---
*Generated by the Starter Packs plugin.*
`;

export async function saveChecklistNote(app: App): Promise<TFile> {
  return writeUniqueNote(app, "Vault replication checklist", VAULT_REPLICATION_CHECKLIST);
}
